-- Seed data for product catalog validation.
-- IDs and prices are aligned with app/data/orderMenu.ts generation.

insert into public.categories (id, name, display_order)
values
  ('wraps-flatbreads-bagels', 'WRAPS FLATBREADS + BAGELS', 1),
  ('porridges', 'PORRIDGES', 2),
  ('toasts', 'TOASTS', 3),
  ('sweet-treats', 'SWEET TREATS', 4),
  ('extra-toppings', 'EXTRA TOPPINGS', 5),
  ('bowls', 'ANOTHER BOWL', 6),
  ('smoothies', 'ANOTHER SMOOTHIE', 7),
  ('another-matcha', 'ANOTHER MATCHA', 8),
  ('another-sip', 'ANOTHER SIP', 9),
  ('another-coffee', 'ANOTHER COFFEE', 10),
  ('coffee', 'COFFEE (ICED / HOT)', 11),
  ('extra-flavours', 'EXTRA FLAVOURS', 12),
  ('shots', 'SHOTS', 13)
on conflict (id) do update
set
  name = excluded.name,
  display_order = excluded.display_order;

insert into public.products (id, name, price, category, is_active)
values
  ('wraps-flatbreads-bagels-avo-egg-cheese-wrap-0','AVO, EGG & CHEESE WRAP',7.25,'wraps-flatbreads-bagels',true),
  ('wraps-flatbreads-bagels-tzatziki-halloumi-flatbread-1','TZATZIKI & HALLOUMI FLATBREAD',8.95,'wraps-flatbreads-bagels',true),
  ('wraps-flatbreads-bagels-salmon-cream-cheese-bagel-2','SALMON & CREAM CHEESE BAGEL',7.95,'wraps-flatbreads-bagels',true),
  ('wraps-flatbreads-bagels-avo-tuna-tomato-pesto-wrap-3','AVO, TUNA, TOMATO & PESTO WRAP',7.25,'wraps-flatbreads-bagels',true),
  ('wraps-flatbreads-bagels-avo-egg-halloumi-bagel-4','AVO, EGG & HALLOUMI BAGEL',6.75,'wraps-flatbreads-bagels',true),
  ('wraps-flatbreads-bagels-hot-honey-halloumi-tacos-5','HOT HONEY HALLOUMI TACOS',11.95,'wraps-flatbreads-bagels',true),
  ('wraps-flatbreads-bagels-bowl-of-homemade-tortilla-chips-6','BOWL OF HOMEMADE TORTILLA CHIPS',5.95,'wraps-flatbreads-bagels',true),
  ('porridges-plain-porridge-0','PLAIN PORRIDGE',7.95,'porridges',true),
  ('porridges-coconut-porridge-1','COCONUT PORRIDGE',7.95,'porridges',true),
  ('porridges-bluberry-porridge-2','BLUBERRY PORRIDGE',7.95,'porridges',true),
  ('porridges-chocolate-banana-3','CHOCOLATE BANANA',7.95,'porridges',true),
  ('porridges-apple-cinnamon-4','APPLE CINNAMON',7.95,'porridges',true),
  ('toasts-avocado-toast-0','AVOCADO TOAST',7.25,'toasts',true),
  ('toasts-tuna-on-toast-1','TUNA ON TOAST',8.25,'toasts',true),
  ('toasts-scrambled-egg-on-toast-2','SCRAMBLED EGG ON TOAST',7.25,'toasts',true),
  ('toasts-pesto-mozzarella-tomato-toast-3','PESTO, MOZZARELLA & TOMATO TOAST',8.25,'toasts',true),
  ('toasts-make-your-own-toast-4','MAKE YOUR OWN TOAST',7.25,'toasts',true),
  ('sweet-treats-banana-bread-0','BANANA BREAD',3.00,'sweet-treats',true),
  ('sweet-treats-chocolate-banana-pancakes-1','CHOCOLATE & BANANA PANCAKES',10.95,'sweet-treats',true),
  ('sweet-treats-berry-pancakes-2','BERRY PANCAKES',10.95,'sweet-treats',true),
  ('sweet-treats-matcha-pancakes-3','MATCHA PANCAKES',10.95,'sweet-treats',true),
  ('extra-toppings-fruits-0','FRUITS',1.00,'extra-toppings',true),
  ('extra-toppings-seeds-nuts-1','SEEDS & NUTS',0.50,'extra-toppings',true),
  ('extra-toppings-sauces-spreads-2','SAUCES & SPREADS',0.50,'extra-toppings',true),
  ('bowls-a-a-0','Açaí',8.75,'bowls',true),
  ('bowls-chocolate-banana-bowl-1','CHOCOLATE BANANA BOWL',8.25,'bowls',true),
  ('bowls-strawberry-mango-bowl-2','STRAWBERRY MANGO BOWL',8.25,'bowls',true),
  ('bowls-pineapple-bowl-3','PINEAPPLE BOWL',8.25,'bowls',true),
  ('bowls-superfood-bowl-4','SUPERFOOD BOWL',8.25,'bowls',true),
  ('bowls-sunrise-bowl-5','SUNRISE BOWL',8.25,'bowls',true),
  ('bowls-strawberries-cream-6','STRAWBERRIES & CREAM',8.25,'bowls',true),
  ('bowls-pb-bowl-7','PB BOWL',8.25,'bowls',true),
  ('bowls-biscoff-bowl-8','BISCOFF BOWL',8.25,'bowls',true),
  ('bowls-yoghurt-bowl-9','YOGHURT BOWL',8.25,'bowls',true),
  ('smoothies-a-a-0','Açaí',6.95,'smoothies',true),
  ('smoothies-breakfast-smoothie-1','BREAKFAST SMOOTHIE',6.50,'smoothies',true),
  ('smoothies-sahara-desert-2','SAHARA DESERT',6.50,'smoothies',true),
  ('smoothies-bananarama-3','BANANARAMA',6.50,'smoothies',true),
  ('smoothies-pb-legend-4','PB LEGEND',6.50,'smoothies',true),
  ('smoothies-blue-mood-5','BLUE MOOD',6.50,'smoothies',true),
  ('smoothies-supergreen-6','SUPERGREEN',6.50,'smoothies',true),
  ('smoothies-exotic-7','EXOTIC',6.50,'smoothies',true),
  ('smoothies-wavey-baby-8','WAVEY BABY',6.50,'smoothies',true),
  ('smoothies-mango-strawberry-9','MANGO & STRAWBERRY',6.50,'smoothies',true),
  ('smoothies-sunburst-smoothie-10','SUNBURST SMOOTHIE',6.50,'smoothies',true),
  ('smoothies-create-your-own-11','CREATE YOUR OWN',6.50,'smoothies',true),
  ('another-matcha-vanilla-matcha-0','VANILLA MATCHA',4.00,'another-matcha',true),
  ('another-matcha-strawberry-mango-juice-matcha-1','STRAWBERRY, MANGO JUICE & MATCHA',4.00,'another-matcha',true),
  ('another-matcha-matcha-fruit-twist-2','MATCHA FRUIT TWIST',4.00,'another-matcha',true),
  ('another-matcha-blueberry-matcha-3','BLUEBERRY MATCHA',4.00,'another-matcha',true),
  ('another-matcha-white-chocolate-matcha-4','WHITE CHOCOLATE MATCHA',4.00,'another-matcha',true),
  ('another-matcha-white-chocolate-raspberry-5','WHITE CHOCOLATE & RASPBERRY',4.95,'another-matcha',true),
  ('another-matcha-pistachio-chocolate-matcha-6','PISTACHIO & CHOCOLATE MATCHA',4.95,'another-matcha',true),
  ('another-matcha-banoffee-pie-matcha-7','BANOFFEE PIE MATCHA',4.95,'another-matcha',true),
  ('another-matcha-raspberry-ripple-matcha-8','RASPBERRY RIPPLE MATCHA',4.95,'another-matcha',true),
  ('another-matcha-exotic-matcha-9','EXOTIC MATCHA',4.95,'another-matcha',true),
  ('another-sip-passionfruit-lemonade-0','PASSIONFRUIT LEMONADE',4.50,'another-sip',true),
  ('another-sip-pineapple-agave-lemonade-1','PINEAPPLE & AGAVE LEMONADE',4.50,'another-sip',true),
  ('another-sip-raspberry-lemon-cooler-2','RASPBERRY & LEMON COOLER',4.50,'another-sip',true),
  ('another-sip-pina-cooler-3','PINA-COOLER',4.25,'another-sip',true),
  ('another-sip-peach-iced-tea-4','PEACH ICED TEA',4.25,'another-sip',true),
  ('another-sip-peach-passionfruit-iced-tea-5','PEACH & PASSIONFRUIT ICED TEA',4.25,'another-sip',true),
  ('another-sip-tropical-iced-tea-6','TROPICAL ICED TEA',4.25,'another-sip',true),
  ('another-sip-berry-iced-tea-7','BERRY ICED TEA',4.25,'another-sip',true),
  ('another-sip-pineapple-mango-juice-8','PINEAPPLE & MANGO JUICE',3.95,'another-sip',true),
  ('another-sip-freshly-squeezed-orange-juice-9','FRESHLY SQUEEZED ORANGE JUICE',3.95,'another-sip',true),
  ('another-coffee-iced-white-mocha-0','ICED WHITE MOCHA',4.25,'another-coffee',true),
  ('another-coffee-midnight-citrus-mocha-1','MIDNIGHT CITRUS MOCHA',4.25,'another-coffee',true),
  ('another-coffee-banana-mocha-bliss-2','BANANA MOCHA BLISS',4.25,'another-coffee',true),
  ('another-coffee-crunch-cream-latte-3','CRUNCH & CREAM LATTE',4.25,'another-coffee',true),
  ('another-coffee-blush-brew-4','BLUSH & BREW',4.25,'another-coffee',true),
  ('coffee-espresso-0','ESPRESSO',2.75,'coffee',true),
  ('coffee-latte-1','LATTE',3.25,'coffee',true),
  ('coffee-cappucino-2','CAPPUCINO',3.25,'coffee',true),
  ('coffee-americano-3','AMERICANO',3.25,'coffee',true),
  ('coffee-mocha-4','MOCHA',3.50,'coffee',true),
  ('coffee-matcha-latte-5','MATCHA LATTE',4.00,'coffee',true),
  ('coffee-tea-herbal-tea-6','TEA / HERBAL TEA',2.75,'coffee',true),
  ('extra-flavours-flavoured-syrups-cold-foams-0','FLAVOURED SYRUPS & COLD FOAMS',1.00,'extra-flavours',true),
  ('extra-flavours-available-flavours-1','AVAILABLE FLAVOURS',1.00,'extra-flavours',true),
  ('shots-honey-lemon-ginger-shot-0','HONEY, LEMON & GINGER SHOT',2.50,'shots',true),
  ('shots-orange-ginger-turmeric-honey-shot-1','ORANGE, GINGER, TURMERIC & HONEY SHOT',2.50,'shots',true)
on conflict (id) do update
set
  name = excluded.name,
  price = excluded.price,
  category = excluded.category,
  is_active = excluded.is_active;
